### ISSUE TITLE
Enchantment table not able to reach full power

### ISSUE THREAD

**Issue by dactel** [Fuzss/enchantinginfuser-fabric#4]
Because the enchantment infusers only scan for books in the 1st and 2nd layers of a typical enchantment table's setup (the gap with the layers of bookshelves, the max enchanting output possible is 24... it does not scan for more than 24, it's impossible to get 30 registered by the enchantment infuser...

EnchantingInfuser-v3.1.1-1.18.1-Fabric.jar version 1.18.1

**Comment by dactel** [comment]
Alright well I figured out that you have to fill in the corners, which is not what I would normally assume, but still, the enchantment table doesn't scan the third row which means that you have to fully surround the table which I don't personally like

**Comment by Fuzss** [comment]
Hi, I hoped it would be more intuitive since the way the enchanting infuser scans for bookshelves is the exact same way it used to be done in vanilla before 1.3, but I guess not too many people seem to remember that (was almost 10 years ago now haha).

I'll tweak this in the next update to let the table scan on 4 layers instead of 2.
