### ISSUE TITLE
Cost modifications arent working

### ISSUE THREAD

**Issue by uhhams** [Fuzss/enchantinginfuser-fabric#6]
im trying to change the costs for enchantments but I dont think im understanding it fully. im trying to make common enchants cost 5 levels per tier, uncommon 8 levels per tier, rare enchants 12 levels per tier, and very rare enchants 18 levels per tier. I edited them this way in the config, but it somehow made it cheaper. what do I do?

<img width="1050" alt="Screen Shot 2022-04-25 at 9 25 50 PM" src="https://user-images.githubusercontent.com/96365922/165221138-3908292f-9c9c-42f9-b0f3-1aca886cc0dc.png">

**Comment by Fuzss** [comment]
You also need to increase the maximum cost for both infusers. I‘ll try to clarify the descriptions in a future update.

**Comment by uhhams** [comment]
increase them to what? also cool that'll definitely be helpful for people !

**Comment by Fuzss** [comment]
To the value which you want fully enchanting an item with all it’s possible enchantments to cost. The rarity costs you already changed are more like weights honestly, the maximum cost has a far stronger influence. 

The system is designed like that since the number of available enchantments varies a lot between different items (e.g. fishing rods have 3 enchants, bows have 5), but I wanted all items to cost the same when maxing out enchants. Kinda like the vanilla enchanting table with the 30 levels limit.

**Comment by uhhams** [comment]
could you give me an example of how the current 25 max level effects the cost? i don't fully understand.

**Comment by Fuzss** [comment]
You enchant a fishing rod with all possible maxed out enchants (luck of the see, unbreaking, lure), it's gonna cost 25 levels in total. You enchant a bow with all possible enchants (power, infinity, unbreaking, punch, flame), it'll cost 25 levels as well, even though that are 5 enchants instead of 3 as with the fishing rod. the idea is that enchantment costs for an item with many enchants don't go out of control (this does not apply to enchanted books).

you can go over 25 levels though when modded enchants are present, or when there are too many individual operations (one operation=increasing any enchant by one level, this always costs at least a single level)

the individual settings for rarities mainly define how those 25 levels are spread out among individual enchants if that makes any sense. as mentioned the main idea behind the 25 level cap is to not make costs explode which is more important to me than being able to precisely control rarity costs

**Comment by uhhams** [comment]
ok that makes sense, thanks!

**Comment by uhhams** [comment]
it doesnt seem to be working, the costs are the same, is there any specific way the config file should be?
also the treasure and modded enchants arent loading on my server, but appear on singleplayer.

**Comment by Fuzss** [comment]
Changing `maximum_power_normal` and `maximum_power_advanced` does what you want, that works fine. No need even to change the rarity costs then, the options work fine by themselves. Just make sure you edit the correct config for your server (it's different from per world, so editing the config of a singleplayer world will not affect your server, use a mod such as [this](https://www.curseforge.com/minecraft/mc-mods/config-menus-forge) one to edit the config on your server from in-game).
~~I also noticed modded enchantments missing just now, that's odd, they were working fine...
Maybe due to a Forge change, I'll look into it at some point.~~ - oversaw it was a treasure enchantment

**Comment by Fuzss** [comment]
This should be resolved.
